services: 
  api_1:
    build: .
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis-db:6379
    command: node server.js
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      redis-db:
        condition: service_healthy
  api_2:
    build: .
    ports:
      - "3002:3000"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis-db:6379
    command: node server.js
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      redis-db:
        condition: service_healthy
  redis-db:
    image: redis:alpine
    volumes:
      - redist_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    container_name: session_db
volumes:
  redist_data: