services: 
  api:
    build: .
    ports:
      - "3000:5001"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis-db:6379
    command: npm run dev
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      redis-db:
        condition: service_healthy
  redis-db:
    image: redis:alpine
    volumes:
      - redist_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
volumes:
  redist_data: